#!/usr/bin/ruby
require 'garfio'

print "post-receive\n"

hook = Garfio::Hook.new
hook.working_dir = '/tmp/dummy_working_directory'
hook.working_branch = 'master'
hook.exec do
  run_if('dummy.rb') do
    run 'pwd'
    run 'cat dummy.rb'
  end
end
